### ISSUE TITLE
Bad mesure ?

### ISSUE THREAD

**Issue by jeff38100** [slametps/MMM-NetworkConnection#4]
Hi,

I have two différents mesurement :
## Speed test:
- Ping = 9.487 ms
- Download = 87.91 Mbit /s
- Upload = 82.94 Mbit /s

## This module:
- Ping = 244 ms
- Download = 14.2 Mbps
- Upload = 10.1 Mbps

What's wrong ?

**Comment by Glass92** [comment]
I get the same;

**Comment by Glass92** [comment]
I think you can choose a specific server by adding 
`serverId: "XXXXX" `
to the config section. 

From the speedtest-net site: https://www.npmjs.com/package/speedtest-net they have a [list of server urls](https://www.npmjs.com/package/speedtest-net) in which you can search for a server near use. For example I did a find for "GB" and that returned servers in Great Britain.

But I have no way of checking other than it seeming to be faster speeds and better ping than the default. Maybe you could figure it out?

Edit: 
I installed speed test on the pi
`npm install --save speedtest-net`
`sudo npm install --global speedtest-net`

then ran 
`speedtest-net`

and got a better ping and download speed than the module.

Hmmmm
